const mongoose = require('mongoose');

const dailyChallengeSchema = new mongoose.Schema({
  question: { type: mongoose.Schema.Types.ObjectId, ref: 'CodingQuestion', required: true },
  date: { type: String, required: true, unique: true }, // 'YYYY-MM-DD'
  referenceLanguage: { type: String, default: 'python' },
  referenceCode: { type: String, default: '' },
  // Expected outputs generated by running reference code
  generatedOutputs: [{ input: String, output: String }],
  solvedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  postedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

module.exports = mongoose.model('DailyChallenge', dailyChallengeSchema);
